import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import  Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
  
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  
}) {

  return (
    <html lang="en">
      <body className={inter.className}>

          <div className="overflow-hidden">
            <div className="h-[10vh]">
              <Navbar />
            </div>
            <div className="flex flex-col max-h-min bg-slate-950">
              {children}
            </div>
          </div>

      </body>
    </html>
  );
}
